### ISSUE TITLE
iPhone Xだと、上の切り込みに刺さります

### ISSUE THREAD

**Issue by makoto1899** [magickworx/PageMenuKitSwift#1]
便利に使わさせていただいております。

Xcode 9のエミュレータで、iPhone Xを動作を確認したところ、
iPhone Xの上部切れ込みにタブが刺さるように見受けられます。

対策方法はありますか?

**Comment by magickworx** [comment]
まだ、Xcode 9 をインストールしていないので、詳しい調査はできないですが、
https://qiita.com/usagimaru/items/761e9a5f3d78b1939df8 の記事にあるように、セーフエリアを考慮しないとダメなようですね。
iPhone X デバイスの場合のみ、PMKPageMenuController の initializer で topBarHeight の値に 145 を指定することで回避できないでしょうか。

**Comment by magickworx** [comment]
同梱の Demo を実行しましたが、iPhone X の画面でも問題ないように思えます。
![iphonex](https://user-images.githubusercontent.com/1241170/30770745-527fc548-a073-11e7-9071-72e7595722a5.png)
