### ISSUE TITLE
Cannot override mutable property 'borderColor' of type 'UIColor?' with covariant type 'UIColor'

### ISSUE THREAD

**Issue by katafuchix** [magickworx/PageMenuKitSwift#3]
PMKPageMenuItem.swift
<img width="783" alt="2018-10-05 14 35 11" src="https://user-images.githubusercontent.com/6063541/46517815-0ba39480-c8ac-11e8-856d-cab6eeb38bcc.png">

**Comment by majithg** [comment]
same here

**Comment by magickworx** [comment]
Try latest repository.
