### ISSUE TITLE
How to set scrolling through code

### ISSUE THREAD

**Issue by anwent** [magickworx/PageMenuKitSwift#5]
`menuKit?.moveIndicator(at: 2)
        menuKit?.currentIndex = 2`

I set these two properties, but the bottom viewController does not scroll, what should I do, thank you my friend

**Comment by anwent** [comment]
@magickworx

**Comment by magickworx** [comment]
These function and property are not public. 
So I think you need not operate  them directly.
If you set  currentIndex=2 at initializer in subclass, you have to use defer.

**Comment by anwent** [comment]
Ok, thank you very much, this library is great.
